### PR TITLE
Enforced sdm local cache path on FileSystemGoalCache

### PR DESCRIPTION
**Pull request by lievendoclo**

### CODE REVIEW

**Comment by cdupuis** [comment]
Not sure the display of cache creation justifies an additional required name. Couldn’t we make that optional or use the classifiers for display?

**Comment by cdupuis** [comment]
Also the build failed

**Comment by cdupuis** [comment]
@lievendoclo still my comment about name. Could we just use the classifier?

**Comment by lievendoclo** [comment]
Sure, I just pushed a change that removes the name.

**Pull request merged**
